### ISSUE TITLE
Warning: Homepage URL matches documentation URL 

### ISSUE THREAD

**Issue by lanzone1** [cloudview-tech/google-tag-manager-base-code#1]
Hi,

When reviewing your template, we noticed that the homepage URL and the documentation URL are the same. Please either remove the documentation URL or set it to a different page.

Thanks.

**Comment by cloudview-tech** [comment]
Hi, @lanzone1 

We have add the documentation last week ([#2091fe1](https://github.com/cloudview-tech/google-tag-manager-base-code/commit/2091fe1d90296681993f3724e53aa727bc165c6c)), please reveiw the template again. Looking forward to your feedback.

Thanks.

**Comment by lanzone1** [comment]
Looks great. Expect your template to be approved shortly. Thanks!
